# Generated by Django 5.1.7 on 2025-03-12 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std_crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='passwords',
            new_name='password',
        ),
    ]
